# fly.toml app configuration file generated for dinkdonk on 2024-07-01T04:55:16+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dinkdonk'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

 [[services.ports]]
 http_options = { response = { headers = { via = false, x-request-start = false, fly-client-ip = false, x-forwarded-for = false, fly-forwarded-proto = false, x-forwarded-proto = false , fly-forwarded-ssl = false, x-forwarded-ssl = false, fly-forwarded-port = false, x-forwarded-port = false, fly-region = false, fly-request-id = false, fly-tracestate = false, fly-traceparent = false } } } 

[[vm]]
  size = 'shared-cpu-1x'
