services:
  backend:
    build:
      context: ../server
      dockerfile: Dockerfile
    restart: unless-stopped
    user: root
    working_dir: /app
    env_file:
      - ../server/.env.development
    environment:
      NODE_ENV: development
      PORT: 3000
    volumes:
      - ../server:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
