name: Deploy Commands to Discord

on:
  push:
    tags:
      - "deploy-discord-*"

jobs:
  deploy-commands:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 📦 Install dependencies
        working-directory: ./server
        run: npm ci

      - name: 🚀 Deploy application commands to Discord
        working-directory: ./server
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
        run: node deploy-commands.js
