name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          OWNER_DM_CHANNEL: ${{ secrets.OWNER_DM_CHANNEL }}
          TWITCH_WEBHOOK_SECRET: ${{ secrets.TWITCH_WEBHOOK_SECRET }}
          PORT: ${{ vars.PORT }}
          WEBHOOK_URL: ${{ vars.WEBHOOK_URL }}
